services:
  - type: web
    name: tehran-house-price
    runtime: python
    plan: free
    region: frankfurt
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port $PORT --server.address 0.0.0.0 --server.headless true
    healthCheckPath: /_stcore/health
    autoDeployTrigger: commit
